{% set version = "1.2.7" %}

package:
  name: fcitx-qt5
  version: {{ version }}

source:
  url: https://github.com/fcitx/fcitx-qt5/archive/{{ version }}.tar.gz
  sha256: 4c1c5e4f9c9067f7274a23411599f8510f52d4fa892c87af63466ec806667823

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxext') }}
    - {{ compiler("cxx") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - qt-main   # [build_platform != target_platform]
  host:
    - xorg-libxfixes
    - libxkbcommon
    - qt-main
    - extra-cmake-modules
  run:
    - libxkbcommon

test:
  commands:
    - test -f ${PREFIX}/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so


about:
  home: https://fcitx-im.org/wiki/Fcitx
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Fcitx [ˈfaɪtɪks] is an input method framework with extension support.
  description: |
    Fcitx [ˈfaɪtɪks] is an input method framework with extension support.
  doc_url: https://fcitx-im.org/wiki/Fcitx
  dev_url: https://github.com/fcitx/fcitx-qt5

extra:
  recipe-maintainers:
    - looooo
